In [1]:
# Slice elements from index 1 to index 6 from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:6])

[2 3 4 5 6]


In [2]:
# Slice elements from index 3 to the end of the array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[3:])

[4 5 6 7]


In [5]:
# Slice elements from the beginning to index 4 (not included):

arr = np.array([2, 5, 6, 7, 8, 9])
print(arr[:4])

[2 5 6 7]


# Negative Slicing

Use the minus operator to refer to an index from the end:

In [6]:
# Slice from the index 3 from the end to index 1 from the end:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


# STEP

Use the step value to determine the step of the slicing:

In [7]:
# Return every other element from index 1 to index 5:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [10]:
# Return every other element from the entire array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])


[1 3 5 7]


# Slicing 2-D Arrays

In [11]:
# From the second element, slice elements from index 1 to index 4 (not included):

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [17]:
# From both elements, return index 2:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2,2])

[3 8]


In [20]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
