# Numpy

In [2]:
import numpy as np

# NumPy Creating Arrays

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# Use a tuple to create a NumPy array:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)


[1 2 3 4 5]


# 0-D Arrays

In [5]:
arr = np.array(42)

print(arr)


42


# 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [6]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [8]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

arr = np.array([[1, 2, 3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


# 3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [15]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [17]:
h = np.array(42)
i = np.array([1, 2, 3, 4, 5])
j = np.array([[1, 2, 3], [4, 5, 6]])
k = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(h.ndim)
print(i.ndim)
print(j.ndim)
print(k.ndim)

0
1
2
3


# Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [24]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:

arr = np.array([1,2,3,4], ndmin =5)
print(arr)
print('number of dmin:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dmin: 5
